### ISSUE TITLE
Problem with node pre-gyp while npm install firebase

### ISSUE THREAD

**Issue by JulienYenne** [nodejs/node-gyp#1842]
I got a problem when trying to execute the following instruction in my Angular project :

npm install firebase --save

Here is the result I obtain :

```
> grpc@1.22.2 install C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.22.2 and node@10.13.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 104.28.22.74:443
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jhardouineau\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\jhardouineau\\Documents\\Formation\\OpenClassrooms\\Angular\\bookshelves\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\jhardouineau\\Documents\\Formation\\OpenClassrooms\\Angular\\bookshelves\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64" "--python=C:\\Python27" "--msvs_version=2017"
gyp ERR! cwd C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jhardouineau\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64 --python=C:\Python27 --msvs_version=2017' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jhardouineau\\Documents\\Formation\\OpenClassrooms\\Angular\\bookshelves\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc
node-pre-gyp ERR! node -v v10.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\jhardouineau\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\jhardouineau\Documents\Formation\OpenClassrooms\Angular\bookshelves\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=3 --node_abi_napi=napi
--napi_build_version=0 --node_napi_label=node-v64 --python=C:\Python27 --msvs_version=2017' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\karma\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\@angular\compiler-cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jhardouineau\AppData\Roaming\npm-cache\_logs\2019-07-23T12_09_45_790Z-debug.log
```

I tried different solutions but nothing worked, maybe I missed something, let me know if you can help,

Thanks

**Comment by JulienYenne** [comment]
Nobody...?

**Comment by AlexanderOrr** [comment]
Same problem but no solution on my end currently

**Comment by joaocgreis** [comment]
This seems to be an issues with the firebase or grpc modules.

@JulienYenne I suggest you try to run `npm install grpc --verbose`. If that succeeds, open an issue with the firebase module. If it fails, open an issue with the grpc module.

I'll close this issue here since this does not seem to be a problem with node-gyp, we can always reopen if there's evidence otherwise.

**Comment by moodywaa555** [comment]
same problem? any help  guys

**Comment by cclauss** [comment]
@moodywaa555 What was the output of __npm install grpc --verbose__ for you?

**Comment by muheebolakunle** [comment]
I'm having the same issue
I ran `npm install grpc --verbose` and it outputed **OK**

**Comment by Danushka96** [comment]
same here. Ubuntu 19.10 with node version 12.7.0

**Comment by Kotovaa** [comment]
I have same problem.
but after I run npm install grpc --verbose
I have this error

`gyp http GET https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.0' ]
gyp verb remove using node-gyp dir: C:\Users\aleksandr.kotov\.node-gyp
gyp verb remove removing target version: 10.16.0
gyp verb remove removing development files for version: 10.16.0
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=C:\\Users\\aleksandr.kotov\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown\\grpc_node.node" "--module_name=grpc_node" "--module_path=C:\\Users\\aleksandr.kotov\\node_modules\\grpc\\src\\node\\extension_binary\\node-v64-win32-x64-unknown" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd C:\Users\aleksandr.kotov\node_modules\grpc
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\aleksandr.kotov\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\aleksandr.kotov\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\aleksandr.kotov\node_modules\grpc\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aleksandr.kotov\\node_modules\\grpc\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd C:\Users\aleksandr.kotov\node_modules\grpc
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --library=static_library --module=C:\Users\aleksandr.kotov\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node --module_name=grpc_node --module_path=C:\Users\aleksandr.kotov\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
npm verb lifecycle grpc@1.22.2~install: unsafe-perm in lifecycle true
npm verb lifecycle grpc@1.22.2~install: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\aleksandr.kotov\node_modules\grpc\node_modules\.bin;C:\Users\aleksandr.kotov\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\aleksandr.kotov\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files (x86)\Common Files\Microsoft Shared\Microsoft Online Services;C:\Program Files\Java\jdk1.8.0_144\bin;C:\Oracle\product\11.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Kaspersky Lab\Kaspersky Endpoint Security 10 for Windows SP1;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\TortoiseSVN\bin;C:\apache-maven-3.5.0-bin\apache-maven-3.5.0\bin;C:\Python27;C:\Users\konstantin.shirokiy\Downloads\node-v8.15.0-win-x64;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Users\aleksandr.kotov\AppData\Roaming\npm;C:\Users\aleksandr.kotov\AppData\Local\Programs\Microsoft VS Code\bin
npm verb lifecycle grpc@1.22.2~install: CWD: C:\Users\aleksandr.kotov\node_modules\grpc
npm info lifecycle grpc@1.22.2~install: Failed to exec install script
npm timing action:install Completed in 33589ms
npm verb unlock done using C:\Users\aleksandr.kotov\AppData\Roaming\npm-cache\_locks\staging-5ab26c5a45d76d2f.lock for C:\Users\aleksandr.kotov\node_modules\.staging
npm timing stage:rollbackFailedOptional Completed in 537ms
npm timing stage:runTopLevelLifecycles Completed in 41591ms
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\aleksandr.kotov\package.json'
npm verb enoent This is related to npm not being able to find a file.
npm verb enoent
npm WARN aleksandr.kotov No description
npm WARN aleksandr.kotov No repository field.
npm WARN aleksandr.kotov No README data
npm WARN aleksandr.kotov No license field.

npm verb stack Error: grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:198:13)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb pkgid grpc@1.22.2
npm verb cwd C:\Users\aleksandr.kotov
npm verb Windows_NT 6.1.7601
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "grpc" "--verbose"
npm verb node v10.16.0
npm verb npm  v6.9.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 42575ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aleksandr.kotov\AppData\Roaming\npm-cache\_logs\2019-08-01T13_17_50_775Z-debug.log`

**Comment by Raunakkmrr** [comment]
Was the problem solved?

Can anybody please tell me, as i am not able to find the solution. @Kotovaa 

Thanks.

**Comment by rvagg** [comment]
```
`gyp http GET https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.16.0' ]
gyp verb remove using node-gyp dir: C:\Users\aleksandr.kotov.node-gyp
gyp verb remove removing target version: 10.16.0
gyp verb remove removing development files for version: 10.16.0
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
gyp ERR! stack at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
```

Looks like a download problem to me - can you download https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz manually? Could you have firewall rules that are stopping `node` from fetching it?

**Comment by nntverd** [comment]
Hi!
I solved problem with firebase. Thanks this guy [Dmitriy Kashirin](https://ru.stackoverflow.com/users/304673/dmitriy-kashirin) on this russian page [page](https://ru.stackoverflow.com/questions/908529/npm-install-firebase-%D0%B2%D1%8B%D0%B4%D0%B0%D0%B5%D1%82-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D1%83) .
He recomended to install python 2.7 with next command
`npm install --global --production windows-build-tools`

and then, it is really important, execute next command (in windows)
`setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"`

after 3 days of search.... ta-da-da-dam... I have working firebase. 

Thanks a lot to Dmitriy. Please, say "Thanks" to him personally

**Comment by Raunakkmrr** [comment]
Hi.!
@nntverd 
but i am working on ubuntu.
ho do i fix my problem.?

**Comment by Danushka96** [comment]
Hi, @Raunakkmrr 
I could fix this error with downgrading the node version to 10.16.0 in Ubuntu 19.10!

**Comment by nntverd** [comment]
> Hi.!
> @nntverd
> but i am working on ubuntu.
> ho do i fix my problem.?

Sorry, bro
I am only begginer in both linux and node js.

More over, yesturday I tried to install firebase in my second project and again had a bunch of errors.
That time solution was to stop Windows Defender.

May be its time to write a paper to google. They have to make full guide how to solve problems with their packages. There is no many node modules that have so many problem with installation and have no clear solution.

Can you support me with writing that papaer?

**Comment by Raunakkmrr** [comment]
Hi, @Danushka96 
i am using ubuntu 18.04 and node version 10.15.3
but still i am getting the problem`grpc@1.22.2 install /home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/bin/node',
node-pre-gyp verb cli   '/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build',
node-pre-gyp verb cli   '--library=static_library' ]
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@8.10.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" (not found)
node-pre-gyp WARN Pre-built binaries not installable for grpc@1.22.2 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node' 
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'clean' ]
gyp info using node-gyp@5.0.3
gyp info using node@8.10.0 | linux | x64
gyp verb command clean []
gyp verb clean removing "build" directory
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--fallback-to-build',
gyp verb cli   '--library=static_library',
gyp verb cli   '--module=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node',
gyp verb cli   '--module_name=grpc_node',
gyp verb cli   '--module_path=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc',
gyp verb cli   '--napi_version=1',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v57' ]
gyp info using node-gyp@5.0.3
gyp info using node@8.10.0 | linux | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python" can be used
gyp verb find Python - executing "python" to get executable path
gyp verb find Python - executable path is "/usr/bin/python"
gyp verb find Python - executing "/usr/bin/python" to get version
gyp verb find Python - version is "2.7.15"
gyp info find Python using Python version 2.7.15 found at "/usr/bin/python"
gyp verb get node dir no --target version specified, falling back to host node version: 8.10.0
gyp verb command install [ '8.10.0' ]
gyp verb install input version string "8.10.0"
gyp verb install installing version: 8.10.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.10.0
gyp verb build dir attempting to create "build" dir: /home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/build'
gyp ERR! System Linux 4.18.0-25-generic
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.18.0-25-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
npm verb lifecycle grpc@1.22.2~install: unsafe-perm in lifecycle false
npm verb lifecycle grpc@1.22.2~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc/node_modules/.bin:/home/fabonacci/Desktop/native Renters App/app3/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
npm verb lifecycle grpc@1.22.2~install: CWD: /home/fabonacci/Desktop/native Renters App/app3/node_modules/grpc
npm info lifecycle grpc@1.22.2~install: Failed to exec install script
npm timing action:install Completed in 5700ms
npm verb unlock done using /home/fabonacci/.npm/_locks/staging-26650729d6e07044.lock for /home/fabonacci/Desktop/native Renters App/app3/node_modules/.staging
npm timing stage:rollbackFailedOptional Completed in 378ms
npm timing stage:runTopLevelLifecycles Completed in 29131ms
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
npm verb notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64

npm verb stack Error: grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at EventEmitter.emit (events.js:214:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at emitTwo (events.js:126:13)
npm verb stack     at ChildProcess.emit (events.js:214:7)
npm verb stack     at maybeClose (internal/child_process.js:925:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm verb pkgid grpc@1.22.2
npm verb cwd /home/fabonacci/Desktop/native Renters App/app3
npm verb Linux 4.18.0-25-generic
npm verb argv "/usr/bin/node" "/usr/local/bin/npm" "install" "grpc" "--verbose"
npm verb node v8.10.0
npm verb npm  v6.10.2
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.22.2 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.22.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 30827ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fabonacci/.npm/_logs/2019-08-03T05_59_16_507Z-debug.log`

**Comment by Raunakkmrr** [comment]
Yess @nntverd   
I am sure i will.

**Comment by NachoCasta** [comment]
Hey guys, I don't know if it helps any of you, but after some research, I fixed it by upgrading to the latest version of firebase.

**Comment by SamiChab** [comment]
[This answer](https://github.com/grpc/grpc-node/issues/888#issuecomment-516918993) helped me. So I just downgraded node (with nvm) and it worked!

**Comment by philly-vanilly** [comment]
> Hi!
> I solved problem with firebase. Thanks this guy [Dmitriy Kashirin](https://ru.stackoverflow.com/users/304673/dmitriy-kashirin) on this russian page [page](https://ru.stackoverflow.com/questions/908529/npm-install-firebase-%D0%B2%D1%8B%D0%B4%D0%B0%D0%B5%D1%82-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D1%83) .
> He recomended to install python 2.7 with next command
> `npm install --global --production windows-build-tools`
> 
> and then, it is really important, execute next command (in windows)
> `setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"`
> 
> after 3 days of search.... ta-da-da-dam... I have working firebase.
> 
> Thanks a lot to Dmitriy. Please, say "Thanks" to him personally

Didn't work for me. The command installs Python to C:/python27 instead of my_user/.windows-build-tools (there I can only find the installable .msi packages) and even after setting

`setx PYTHON "C:\Python27\python.exe"
`
I still get the same error, that python.exe ould not be executed. I am struggling with this error for three months already, resorting to copying node_modules from colleagues who don't work on windows.

Will somebody please, please fix this some day?

**Comment by cclauss** [comment]
py -2 --version
py -3 --version

**Comment by Alejov0** [comment]
Using `"firebase": "^7.8.2"`  worked for me.

**Comment by Mejerigaarden** [comment]
Using  

    "firebase": "^7.8.2"

had me off the hook (dragging my feet on macOS 10.14.6, yarn 1.19.2, and node v13.2.0)

**Comment by Edebo** [comment]
I installed npm install node-pre-gyp -g on the root user.then tried installing npm i firebase again.this worked for me

**Comment by DonutRanger** [comment]
> Hi!
> I solved problem with firebase. Thanks this guy [Dmitriy Kashirin](https://ru.stackoverflow.com/users/304673/dmitriy-kashirin) on this russian page [page](https://ru.stackoverflow.com/questions/908529/npm-install-firebase-%D0%B2%D1%8B%D0%B4%D0%B0%D0%B5%D1%82-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D1%83) .
> He recomended to install python 2.7 with next command
> `npm install --global --production windows-build-tools`
> 
> and then, it is really important, execute next command (in windows)
> `setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"`
> 
> after 3 days of search.... ta-da-da-dam... I have working firebase.
> 
> Thanks a lot to Dmitriy. Please, say "Thanks" to him personally

This was I wanted. I finally can resume work! But please can someone explain to me what it does? I was desperate so I stuck to this.

**Comment by ubaidillahSriyudi** [comment]
> I had the same problem
> But after I ran `npm install grpc --verbose` it outputed **OK**
> Then firebase installed successfully

thanks, it works for me
npm install grpc --verbose
deleted node_modules & package-lock.json
then re run again

**Comment by pflevy** [comment]
In my case, I rely on a **github action** to handle the build and deploy (through firebase-action).
I fixed this error by changing from the install step from `npm install` to `npm install && npm install firebase`

**Comment by JulienYenne** [comment]
Hi everyone,

This question was related to my job, but I enveutally didn't start to work on Angular.
Anyway thanks for the answers, hope it helped some people :)

**Comment by Gry1005** [comment]
I have the same problem, solved it by downgrading my nodejs from 14. to 10.

**Comment by cclauss** [comment]
@Gry1005 Before downgrading Node.js, did you try `npm install && npm install firebase` as suggested above?  If so, what were the results?

**Comment by Gry1005** [comment]
> 
> 
> @Gry1005 Before downgrading Node.js, did you try `npm install && npm install firebase` as suggested above? If so, what were the results?

I tried that, but I think that npm doesn't support 'npm install && npm install firebase' on win10.

**Comment by cclauss** [comment]
Correct.  On Linux and macOS, `&&` is the way to join two separate commands such that if the first one does not error then the second one is run.

On Windows, you would need to run `npm install` and then afterwards run `npm install firebase`

**Comment by Gry1005** [comment]
> 
> 
> Correct. On Linux and macOS, `&&` is the way to join two separate commands such that if the first one runs without error then the second one is also run.
> 
> On Windows, you would need to run `npm install` and then afterwards run `npm install firebase`

I tried these, and it will output the same error. The only way to solve this problem in this post is downgrading the nodejs on my machine, but I'm not sure the problem is caused by gyp or firebase.
