### ISSUE TITLE
node-gyp rebuild Fails on Mac OS X 10.9.4

### ISSUE THREAD

**Issue by shkfnly** [nodejs/node-gyp#489]
Terminal output

<pre>
<code>
hiredis@0.1.17
node@v0.11.13
node-gyp@v1.0.1
npm@1.4.9

which libtool
/usr/bin/libtool

$ npm install -g hiredis
npm http GET https://registry.npmjs.org/hiredis
npm http 304 https://registry.npmjs.org/hiredis
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> hiredis@0.1.17 install /usr/local/lib/node_modules/hiredis
> node-gyp rebuild

  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  LIBTOOL-STATIC Release/hiredis.a
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
make: *** [Release/hiredis.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046:12)
gyp ERR! System Darwin 13.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hiredis
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm ERR! hiredis@0.1.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hiredis@0.1.17 install script.
npm ERR! This is most likely a problem with the hiredis package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hiredis
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.3.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "hiredis"
npm ERR! cwd /Users/ashokafinley
npm ERR! node -v v0.11.13
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/ashokafinley/npm-debug.log
npm ERR! not ok code 0
</code>
</pre>

**Comment by topherhunt** [comment]
Ditto what @Globegitter said: I've given up trying to get around this failed build on Mac OSX and Node v0.12 (I'm trying to `npm install canvas` which requires `node-gyp`) but once I removed Node and installed version 0.10.9 instead (directly from nodejs.org, rather than via Homebrew), `canvas` and `node-gyp` install fine.

My issue sounds more similar to https://github.com/Homebrew/homebrew/issues/14123 in that the error message when rebuilding node-gyp was `Package 'xcb-shm', required by 'cairo', not found`, but the only solution that's worked for me so far was the Node version downgrade mentioned above.

**Comment by Arkantas** [comment]
http://stackoverflow.com/questions/22100213/package-cairo-was-not-found-in-the-pkg-config-search-path-node-j-s-install-canv
This worked for me (answer by Piyush Dholariya)

**Comment by akhildave** [comment]
@Arkantas  Many Thanks for the link, It really helped me out  :)

**Comment by pipi32167** [comment]
Same problem here. But I found my ```libtool``` is actully ```/opt/chefdk/embedded/bin/libtool```, so ```sudo rm -rf /opt/chefdk``` can solve my problem.

**Comment by kristianmandrup** [comment]
I raised this issue https://github.com/redis/hiredis-node/issues/94

**Comment by mydearxym** [comment]
gyp: binding.gyp not found  ... big pain

**Comment by turboladen** [comment]
I'm on El Capitan (10.11) and @veacks suggestion of `brew unlink libtool` did the trick for me.

**Comment by adriano-di-giovanni** [comment]
Just solved same problem. 

In my case, Mac OS X automatic updates downloaded and installed a new version of XCode.

As you may know, you have to accept the license agreement in order to use both XCode and its command line tools.

`libtool` is one of these command line tools. `libtool` is used by `node-gyp`.

I run `libtool` and accepted license agreement via terminal.

Everything worked soon after.

**Comment by yaron-idan** [comment]
@adriano-di-giovanni, when running libtool I get the following output - 
'error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]'

**Comment by yaron-idan** [comment]
@adriano-di-giovanni, I've tried running libtool to accept the agreement and got this output - 
    error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: no files specified
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -static [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-sacLT] [-no_warning_for_no_symbols]
    Usage: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool -dynamic [-] file [...] [-filelist listfile[,dirname]] [-arch_only arch] [-o output] [-install_name name] [-compatibility_version #] [-current_version #] [-seg1addr 0x#] [-segs_read_only_addr 0x#] [-segs_read_write_addr 0x#] [-seg_addr_table <filename>] [-seg_addr_table_filename <file_system_path>] [-all_load] [-noall_load]

Could you help me solve this please?

**Comment by adriano-di-giovanni** [comment]
Running libtool is just a shortcut to accept license agreement. I don't know why it fails on your machine but you can always open XCode and accept the license agreement. 

Try and please, let me know 😉

Inviato da iPhone

**Comment by yaron-idan** [comment]
True enough, XCode license wasn't my problem, and the license agreement was already accepted (as I found out through opening XCode like you advised)
The problem ended up being node not upgraded to suit El-Capitan, after I upgraded it everything went pretty smooth...

Thank you for the support!

**Comment by adriano-di-giovanni** [comment]
You're welcome 😉

Inviato da iPhone

**Comment by carljokl** [comment]
I am on Yosemite with Node 5.0.0 and have this issue and nothing listed above has fixed the problem.

**Comment by qmmr** [comment]
I've had a similar issue with node-gyp and node v5.0.0 but it turned out to be the xcode that was causing issues. After accepting the license via `sudo xcodebuild -license` it was a smooth ride.

**Comment by mmahalwy** [comment]
@yaron-idan what did you mean you upgraded everything? What'd you upgrade?

**Comment by yaron-idan** [comment]
@mmahalwy My node version was <5.0.0, I don't remember the exact number. After I've upgraded node to 5.0.0 and npm to 3.3.9 the problem was solved.

**Comment by vudodov** [comment]
```bash
xcode-select --install
npm install -g npm@latest
```

worked for me

**Comment by yamii** [comment]
I have darwin and node 5.0 installed `sudo xcodebuild -license` fix my issue. Thanks @qmmr

**Comment by hagenschulze** [comment]
Same problem as @topherhunt while trying to install canvas.
`brew install pkg-config` solved the problem for me.

**Comment by mdodkins** [comment]
this is a useful link... http://flummox-engineering.blogspot.com/2014/04/libtool-unrecognized-option-static.html

basically, if you're using GNU Libtool, you need to unlink it... I had to do this manually because I was using it, but not because of brew...

**Comment by cecilialam** [comment]
@adriano-di-giovanni suggestion works for me.

**Comment by ulesta** [comment]
Ran all the suggested commands above and still didn't work. Restarted my computer and it started working **magically**. So if all fails, try restarting! 👍

**Comment by nihakue** [comment]
I was having this problem on OSX v10.11.5 (15F34) running node v6.2.1 and `sudo xcodebuild -license` seems to have resolved it. Weird.

**Comment by xdamman** [comment]
Same issue with:
 ```
MacOSX 10.11.6 (also tried with MacOSX 10.11.5)
node v.6.3.1 (also tried with node v6.2.2)
npm 3.10.3
python 2.7.10
```

I did `sudo xcodebuild -license`

I did `xcode-select --install`

    xcode-select: error: command line tools are already installed, use "Software Update" to install updates

Still doesn't work.
Then I tried `brew unlink libtool` 

    Error: No such keg: /usr/local/Cellar/libtool

Still doesn't work. Then I tried `brew install pkg-config`

    Warning: pkg-config-0.29.1_1 already installed

Still no luck.
Running out of ideas.

`npm install -g node-gyp` works like a charm.
but `npm install` still fails at:

    > bcrypt@0.8.5 install /Users/xdamman/github/opencollective/api/node_modules/bcrypt
    > node-gyp rebuild

My only luck was to downgrade node to `v5.12.0`.

**Comment by xdamman** [comment]
Update, I solved it.
This was happening when npm was trying to install bcrypt. 

For some reason, within the project, `npm install bcrypt` was failing, but `npm install -g bcrypt` worked. So running within the directory of the project `npm link bcrypt` did the trick.

This is still weird. Not sure what's wrong with my setup.

**Comment by xdamman** [comment]
Update 2: the reason why it was working with `npm -g` is because it was installing bcrypt 0.8.7, whereas within the project directory, it was installing bcrypt 0.8.5. So updating the version number of bcrypt in package.json solved the issue. Mystery solved!

**Comment by afacanerman** [comment]
@xdamman cheers saved my night.

**Comment by mevlutsahinn** [comment]
@xdamman thank you. Worked like charm after trying tons of suggestions.

**Comment by mbutler** [comment]
None of the suggestions in this issue thread worked for me except downgrading node to 6.10.0 LTS

**Comment by intafon** [comment]
@mbutler Same here. I had lwip installing fine running node-gyp rebuild, then updated brew this morning and updated node from 7.7.2 to 7.7.3 and it broke it. After trying many things, finally uninstalled node from brew altogether and installed 6.10.0LTS from nodejs.org...

**Comment by erick2014** [comment]
tested in mac os x 10.11.6, using v6.10.1 and npm 4.4.4, I run npm install -g npm@latest node-gyp, and now I'm able to compile the modules

**Comment by brycereynolds** [comment]
I just encountered this issue and realized that previously I had used `pyenv` and changed my python version. Since it seems to be involved in the compiling of bcrypt (news to me), I had to change my python version back to `2.7.10` to make it work:

`pyenv global 2.7.10`

**Comment by tomchapin** [comment]
I use pyenv to manage my python installations, and I was unable to get node-gyp to build until I explicitly configured npm so that it used the correct python virtualenv shim, like so:
`npm config set python /Users/your_username_here/.pyenv/versions/2.7.10/envs/virtual_env_name_here/bin/python`

**Comment by refack** [comment]
Do you know if `pyenv` has a local registry that `node-gyp` can query (or a stable path)?

**Comment by tomchapin** [comment]
@refack the .pyenv directory is typically at the user's home folder at $HOME/.pyenv but the path can also be determined by evaluating `$(pyenv root)/` or by looking at the `PYENV_ROOT` environment variable.

**Comment by maclover7** [comment]
It _seems_ like general installation issues (XCode license, etc.) was the issue here, as well as running on outdated versions of Node.js and `node-gyp`. Upgrading Node.js / `node-gyp` to a supported version will fix this problem, so going to close this this ticket for now since a fix has been identified.

**Comment by toadead** [comment]
Node v9.11.2 with npm 5.6.0 seemed working for me

**Comment by mattbontrager** [comment]
For anyone who still runs into this issue, here's the fix: `npm config set python /usr/bin/python`.

I _**finally**_ figured out what the actual problem is. npm is being pointed to the userland python (typically installed by brew ... /usr/local/bin/python) not the system level python (/usr/bin/python). I just didn't know that there was a system level python.

**Comment by shaunlebron** [comment]
@mattbontrager's solution fixed it for me.  I had a Python 3 at `/usr/local/bin/python`, and node-gyp needs Python 2 at `/usr/bin/python`

**Comment by simesy** [comment]
`brew upgrade` worked for me. must not have done it since OSX update

**Comment by tamitutor** [comment]
You may want to look at what package you are trying to install.  For instance, the firebase@latest package fails with node-gyp because it has an outdated grpc dependency.  I was trying to do just that and ended up having to downgrade my node version to 10.13.0 in order to avoid the node-gyp build errors when installing firebase.

**Comment by schakra19** [comment]
This helped me solve the problem of node-gyp version - https://github.com/nodejs/node-gyp/wiki/Updating-npm%27s-bundled-node-gyp

**Comment by xXACCEXx** [comment]
I had this issue, not sure how it got there, but the resolution was removing an older package that we had as a dependency. 'gulp-core' which hadn't been updated in 3 years, referring to a really outdated version.

Was a bit annoying, but resolved by removing that package...

Bit of a basic issue, just thought I'd put this here to help others, if they can't figure it out...

**Comment by rajutanniru44** [comment]
i had solved this by downgrading the node and npm versions

### Before versions:
**node - v10.14.2
npm - 6.5.0**

i had downgraded to below versions

### After versions :
**node - v8.11.3
npm - 5.6.0**

this issue will be resolved,please try if any one still facing the issue

**Comment by digvijaymhasaye** [comment]
> ```shell
> xcode-select --install
> npm install -g npm@latest
> ```
> 
> worked for me

npm install -g npm@latest 
Worked for me

**Comment by CodyWalraven** [comment]
Changing my python version to 2.7  via pyenv fixed the issue with fsevents for me! Thanks for the comment about that I was pulling my hair out over this!

**Comment by ximendatie** [comment]
you need install something before installing node-gyp
references：
 https://www.npmjs.com/package/node-gyp

**Comment by v88NoahJerreel** [comment]
thanks @xdamman <3

**Comment by g4d** [comment]
Upgrading node 5 to 8 worked for me.
`nvm install 8`

**Comment by DNXie** [comment]
`npm install node-gyp` solves the problem for me. (MacOS)

**Comment by renjithspace** [comment]
Install node-gyp globally worked for me.
```
$ npm i -g node-gyp
```

**Comment by YuanSamuel** [comment]
I followed the instructions posted here: https://github.com/nodejs/node-gyp/issues/569
and got it working.

**Comment by cooperka** [comment]
MacOS Mojave v10.14 here, I solved it by setting some environment flags:

```
env LDFLAGS="-mmacosx-version-min=10.9" CXXFLAGS="-mmacosx-version-min=10.9" npm install
```

**Comment by facundokantox** [comment]
It needs Python 2.
If you use `pyenv`, to install Python 2 you first need to uninstall openssl
```sh
brew uninstall --ignore-dependencies openssl@1.1
```
Then
```sh 
pyenv install 2.7.9
```
And you will be all set
```sh 
npm install node-gyp
```

You may want to install openssl again:
```sh 
brew install openssl@1.1
```

**Comment by cclauss** [comment]
Nothing needs Python 2 anymore.  Python 2 died on 1/1/2020.

**Comment by facundokantox** [comment]
I know it dies. That set of commands its what worked for me anyway.

On Sat, 23 May 2020 at 16:17, Christian Clauss <notifications@github.com>
wrote:

> Nothing needs Python 2 anymore. Python 2 died on 1/1/2020.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nodejs_node-2Dgyp_issues_489-23issuecomment-2D633062410&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=YbnUj8O00aeWeQQr7OWy6hSnFZZWlMc_xgEDr0oljAk&m=FhkBA-61Pws8Av4ul7JnNryd_C5_BBFSZs_LNqfHawY&s=qA938GEFK1Pd4aUwfaUtTPD82e9hHL-PWCeAEqRu7M4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ANGTBBQSHJXLLQQ5M7BM3Z3RS7LG3ANCNFSM4ASZNO6A&d=DwMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=YbnUj8O00aeWeQQr7OWy6hSnFZZWlMc_xgEDr0oljAk&m=FhkBA-61Pws8Av4ul7JnNryd_C5_BBFSZs_LNqfHawY&s=t1K784gbAe0WuBTmDbqh9dc8IIBQMKANQpIiFUiSBCw&e=>
> .
>
-- 

*Facundo Diaz*, Senior Software Engineer

Office    (+34) 935 679 834 - Ext.

<http://kantox.com> <http://kantox.com/en>

8 Devonshire Square, 5th Floor, London, EC2M 4PL, United Kingdom
Torre Mapfre, Planta 22, Marina, 16-18, 08005 Barcelona, Spain
*kantox.com <http://kantox.com/>*



<http://www.linkedin.com/company/1871617>
<http://www.linkedin.com/company/1871617>[image: LinkedIn]
<https://www.linkedin.com/company/1871617>
<https://twitter.com/kantox>[image:
Twitter] <https://twitter.com/kantox>
<http://www.youtube.com/user/kantoxfx>[image: YouTube]
<https://www.youtube.com/user/kantoxfx>

Kantox Limited is registered in England and Wales as a Limited Company: No
07657495 and is authorised by the Financial Conduct Authority, FRN: 580343,
as a Payments Institution under the Payment Services Regulations 2017. This
email is subject to professional secrecy. It is confidential and for the
exclusive use of its addressee. If you are not the addressee, you are not
authorised to read, keep or disseminate it.

**Comment by AmlanAlok** [comment]
This answer on stack overflow solved it for me - https://stackoverflow.com/a/55590251/10622142

1. Delete package-lock.json
2. Run command => npm install
